package com.example.taskervideoplugin.tasker
import android.content.*;import android.view.LayoutInflater;import com.example.taskervideoplugin.*;import com.example.taskervideoplugin.databinding.ActivityCameraConfigBinding;import com.example.taskervideoplugin.media.*;import com.joaomgcd.taskerpluginlibrary.config.*;import com.joaomgcd.taskerpluginlibrary.input.TaskerInput;import com.joaomgcd.taskerpluginlibrary.action.TaskerPluginRunnerAction;import com.joaomgcd.taskerpluginlibrary.runner.*
abstract class BaseRunner:TaskerPluginRunnerAction<CameraInput,MediaOutput>(){override val notificationProperties get()=NotificationProperties(iconResId=com.example.taskervideoplugin.R.drawable.plugin);fun out(file:java.io.File,res:String?,ms:Long=0)=MediaOutput(file.path,file.parentFile?.path,file.extension,res,ms,ms/1000,ms/60000,"%02d:%02d".format(ms/60000,(ms/1000)%60))}
class StartVideoRunner:BaseRunner(){override fun run(context:Context,input:TaskerInput<CameraInput>)=TaskerPluginResultSucess(input.regular.run{out(CameraController.start(context,recordingId,camera,resolution,path,fileName,format).file,resolution)})}
class PauseVideoRunner:BaseRunner(){override fun run(context:Context,input:TaskerInput<CameraInput>)=TaskerPluginResultSucess(input.regular.run{val r=CameraController.pause(recordingId?:error("recordingId required"),stopAndSave);if(r is Pair<*,*>) out((r.first as Recording).file,resolution,r.second as Long) else out((r as Recording).file,resolution)})}
class ResumeVideoRunner:BaseRunner(){override fun run(context:Context,input:TaskerInput<CameraInput>)=TaskerPluginResultSucess(input.regular.run{out(CameraController.resume(recordingId?:error("recordingId required")).file,resolution)})}
class StopVideoRunner:BaseRunner(){override fun run(context:Context,input:TaskerInput<CameraInput>)=TaskerPluginResultSucess(input.regular.run{val (r,ms)=CameraController.stop(recordingId?:error("recordingId required"));out(r.file,resolution,ms)})}
class TakePhotoRunner:BaseRunner(){override fun run(context:Context,input:TaskerInput<CameraInput>)=TaskerPluginResultSucess(input.regular.run{out(CameraController.photo(path,fileName,format,resolution),resolution)})}
class VideoToFramesRunner:BaseRunner(){override fun run(context:Context,input:TaskerInput<CameraInput>):TaskerPluginResult<MediaOutput>{input.regular.run{FrameExtractor.extract(path,targetPath,baseName,format,frameRate,frames);return TaskerPluginResultSucess(MediaOutput(path,targetPath,format,null))}}}
class AudioBlockRunner:BaseRunner(){override fun run(context:Context,input:TaskerInput<CameraInput>)=TaskerPluginResultSucess(MediaOutput("Audio of other apps cannot be selectively blocked for legacy Tasker scenes by a third-party plugin; mute the scene player or choose stream in the scene.",null,null,null))}
abstract class Helper<R:BaseRunner>(config:TaskerPluginConfig<CameraInput>,private val cls:Class<R>):TaskerPluginConfigHelper<CameraInput,MediaOutput,R>(config){override val runnerClass=cls;override val inputClass=CameraInput::class.java;override val outputClass=MediaOutput::class.java;override val defaultInput=CameraInput();override fun addToStringBlurb(input:TaskerInput<CameraInput>,b:StringBuilder){b.append(input.regular.fileName)}}
abstract class Config<R:BaseRunner,H:Helper<R>>:ActivityConfigTasker<CameraInput,MediaOutput,R,H,ActivityCameraConfigBinding>(){override fun inflateBinding(layoutInflater:LayoutInflater)=ActivityCameraConfigBinding.inflate(layoutInflater);override fun assignFromInput(input:TaskerInput<CameraInput>){input.regular.run{binding?.camera?.setText(camera);binding?.resolution?.setText(resolution);binding?.path?.setText(path);binding?.fileName?.setText(fileName);binding?.format?.setText(format);binding?.recordingId?.setText(recordingId);binding?.stopAndSave?.isChecked=stopAndSave;binding?.targetPath?.setText(targetPath);binding?.baseName?.setText(baseName);binding?.frameRate?.setText(frameRate?.toString());binding?.frames?.setText(frames?.toString())}};override val inputForTasker get()=TaskerInput(CameraInput(binding?.camera?.text?.toString(),binding?.resolution?.text?.toString(),binding?.path?.text?.toString(),binding?.fileName?.text?.toString(),binding?.format?.text?.toString(),binding?.recordingId?.text?.toString(),binding?.stopAndSave?.isChecked?:false,binding?.targetPath?.text?.toString(),binding?.baseName?.text?.toString(),binding?.frameRate?.text?.toString()?.toDoubleOrNull(),binding?.frames?.text?.toString()?.toIntOrNull()))}
class StartVideoHelper(c:TaskerPluginConfig<CameraInput>):Helper<StartVideoRunner>(c,StartVideoRunner::class.java);class StartVideoActivity:Config<StartVideoRunner,StartVideoHelper>(){override fun getNewHelper(config:TaskerPluginConfig<CameraInput>)=StartVideoHelper(config)}
class PauseVideoHelper(c:TaskerPluginConfig<CameraInput>):Helper<PauseVideoRunner>(c,PauseVideoRunner::class.java);class PauseVideoActivity:Config<PauseVideoRunner,PauseVideoHelper>(){override fun getNewHelper(config:TaskerPluginConfig<CameraInput>)=PauseVideoHelper(config)}
class ResumeVideoHelper(c:TaskerPluginConfig<CameraInput>):Helper<ResumeVideoRunner>(c,ResumeVideoRunner::class.java);class ResumeVideoActivity:Config<ResumeVideoRunner,ResumeVideoHelper>(){override fun getNewHelper(config:TaskerPluginConfig<CameraInput>)=ResumeVideoHelper(config)}
class StopVideoHelper(c:TaskerPluginConfig<CameraInput>):Helper<StopVideoRunner>(c,StopVideoRunner::class.java);class StopVideoActivity:Config<StopVideoRunner,StopVideoHelper>(){override fun getNewHelper(config:TaskerPluginConfig<CameraInput>)=StopVideoHelper(config)}
class TakePhotoHelper(c:TaskerPluginConfig<CameraInput>):Helper<TakePhotoRunner>(c,TakePhotoRunner::class.java);class TakePhotoActivity:Config<TakePhotoRunner,TakePhotoHelper>(){override fun getNewHelper(config:TaskerPluginConfig<CameraInput>)=TakePhotoHelper(config)}
class VideoToFramesHelper(c:TaskerPluginConfig<CameraInput>):Helper<VideoToFramesRunner>(c,VideoToFramesRunner::class.java);class VideoToFramesActivity:Config<VideoToFramesRunner,VideoToFramesHelper>(){override fun getNewHelper(config:TaskerPluginConfig<CameraInput>)=VideoToFramesHelper(config)}
class AudioBlockHelper(c:TaskerPluginConfig<CameraInput>):Helper<AudioBlockRunner>(c,AudioBlockRunner::class.java);class AudioBlockActivity:Config<AudioBlockRunner,AudioBlockHelper>(){override fun getNewHelper(config:TaskerPluginConfig<CameraInput>)=AudioBlockHelper(config)}
